---
- name: Setup locale and hostname
  hosts: localhost
  connection: local
  vars:
    timezone: Europe/Berlin
    hostname: archPC
  tasks:
    - name: Uncomment en_US.UTF-8
      replace:
        path: /etc/locale.gen
        regexp: '^#en_US.UTF-8 UTF-8'
        replace: 'en_US.UTF-8 UTF-8'

    - name: Generate locale
      command: locale-gen

    - name: Configure locale.conf
      lineinfile:
        path: /etc/locale.conf
        line: 'LANG=en_US.UTF-8'
        create: yes

    - name: Configure hostname
      lineinfile:
        path: /etc/hosts
        line: '127.0.1.1 localhost.localdomain {{ hostname }}'
        create: yes

    - name: Add localhost to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: '127.0.1.1 localhost.localdomain {{ hostname }}'
        create: yes

    - name: Set time zone to /etc/localtime
      file:
        src: '/usr/share/zoneinfo/{{ timezone }}'
        dest: /etc/localtime
        state: link

    - name: Sync system time with timezone
      shell: hwclock --systohc --utc
